### ISSUE TITLE
It's gone offline

### ISSUE THREAD

**Issue by andrewstech** [Wizqdev/Status-Page-Api#1]
![IMG-20240109-WA0129](https://github.com/Wizqdev/Status-Page-Api/assets/45342431/7b7bd1e0-e14b-47d7-a6c5-58de03a1a84a)

**Comment by wdhdev** [comment]
![Screenshot_20230406_081711_Twitter](https://github.com/Wizqdev/Status-Page-Api/assets/87287585/1520b7fc-359e-479c-99a2-66179f1b71dc)

**Comment by qing762** [comment]
![Suspicious-Dog-meme-1](https://github.com/Wizqdev/Status-Page-Api/assets/59680329/6d7f1eb7-3de8-4f90-bd9a-1ecf2aaf47b6)

**Comment by SukiPlayz** [comment]
![image](https://github.com/Wizqdev/Status-Page-Api/assets/93142236/4bbdb8ca-9aec-4f36-bb64-1db1f32b87ba)

**Comment by m1kuwu** [comment]
![ImgResizer_20240104_1956_10380](https://github.com/Wizqdev/Status-Page-Api/assets/55346436/a86e156d-70c3-40b1-b04e-069bf7e9d538)

**Comment by m1kuwu** [comment]
![mniam-mniamdiscord](https://github.com/Wizqdev/Status-Page-Api/assets/55346436/2705aebd-1109-4703-8f09-aeff085b7ff1)

**Comment by m1kuwu** [comment]
![Uploading pepefrog.gif…]()

**Comment by Wizqdev** [comment]
Flxed Uploaded Files

**Comment by andrewstech** [comment]
![Screenshot_20231217-232259](https://github.com/Wizqdev/Status-Page-Api/assets/45342431/c1998062-1e78-40f7-86e5-f67dd0b57632)
